Suggest a quicker and easier installation method
badboy/mdbook-mermaid pull request #33
Opened 2023-05-13 18:28 UTC by sanmai-NL

This is particularly useful to keep CI pipelines fast and concise.

2023-12-22 14:54 UTC, sanmai-NL commented
@badboy This seems like an easy to review PR after your holidays.

2024-01-05 12:00 UTC, badboy requested changes
Appreciate the work and I will add that install method, but I'm quickly wipping up the commit myself now.

2024-01-05 12:00 UTC, badboy commented on README.md
> +```
No need for the full output, the command is enough.

2024-01-05 12:00 UTC, badboy commented on README.md
> +This installs the right binaries released here on GitHub (which you could also download manually).
Indeed they are and we should call that out!

2024-01-05 12:08 UTC, closed without merging